### ISSUE TITLE
Does this tool currently work?

### ISSUE THREAD

**Issue by amrhamed** [lhm30/PubChem_Inactives#1]
Hello,
I am trying to use this tool but I am not sure if it is working or not...
I am getting [ ] every time as response

**Comment by lhm30** [comment]
Hi. I'm afraid this doesn't work anymore with the new secure ncbi servers

**Comment by amrhamedp** [comment]
Are there any plans to update it or any possible workaround?

**Comment by lhm30** [comment]
Here is an updated version:

It takes only the uniprot 

e.g. 

In [1]: import PubChem_Inactives

In [2]: PubChem_Inactives.uniprot_smiles('A2TJX0')
Out[2]: 
[5767168,
 5767171,
 5767172,
 2097157,
 2097158,
 1048587,
 4194316,

Where the returned items are CID's

**Comment by amrhamed** [comment]
I am not sure if it is updated  but I can't see any commit for the file.

I tried to run above example and it says:

Traceback (most recent call last):
  File "p.py", line 4, in <module>
    PubChem_Inactives.uniprot_smiles('A2TJX0')
  File "/scratch2/rmsd/PubChem_Inactives/PubChem_Inactives.py", line 147, in uniprot_smiles
    gids += uniprot_mapping("ACC","P_ENTREZGENEID",uniprot)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')

**Comment by lhm30** [comment]
are sure you have the dependencies required to run the code too.

I.e. Biopython etc.

**Comment by lhm30** [comment]
Updated to include actives & inactives downloading
